### PR TITLE
Fix address derivation from pubKey

### PR DESCRIPTION
**Pull request by AyushBherwani1998**
Use uncompressed pubKey to derive the address.

### CODE REVIEW

**Comment by AyushBherwani1998** [comment]
There's one issue with implementation, we can't throw the error. So, we have to assume, it's always best case when deriving the address. The error can't be thrown because we have inherit `EthereumAccountProtocol`

**Comment by metalurgical** [comment]
@AyushBherwani1998 

If we have to do this there like you're suggesting there is a larger design problem. The reason it is not throwable there is that it should always be valid by the time it reaches that point, empty is not a valid output either.

Please see the original implementation for where the error for this should be thrown and how it is guaranteed to be valid thereafter:
https://github.com/tkey/web3-swift-mpc-provider/blob/main/Sources/Web3SwiftMpcProvider/EthereumTssAccount.swift#L32-L39

**Comment by AyushBherwani1998** [comment]
@metalurgical the problem is not whether I can throw the error, the problem is that the throwing error doesn't conform to the `address` definition from `EthereumProtocol`. To throw an error I need to use the `throw` keyword to change the definition of the address which doesn't conform to `EthereumProtocol`.

**Comment by metalurgical** [comment]
> @metalurgical the problem is not whether I can throw the error, the problem is that the throwing error doesn't conform to the `address` definition from `EthereumProtocol`. To throw an error I need to use the `throw` keyword to change the definition of the address which doesn't conform to `EthereumProtocol`.

Yes, exactly, the address should have already been validated previously and assigned here, not trying to calculate what the address is here. Like I said, it is a larger design problem with the signing kit.

**Comment by AyushBherwani1998** [comment]
@metalurgical I'm thinking to add the `isCompressed` flag in `getTssPubKey()` of core-kit swift. By default, we can keep it `true` so the existing functionality doesn't break. And if the flag is `false` we return the uncompressed key. I think this will solve the issue. WDYT?

**Comment by metalurgical** [comment]
> @metalurgical I'm thinking to add the `isCompressed` flag in `getTssPubKey()` of core-kit swift. By default, we can keep it `true` so the existing functionality doesn't break. And if the flag is `false` we return the uncompressed key. I think this will solve the issue. WDYT?

It still won't get rid of the `try`.

**Pull request closed without merging**
